//EN ESTE MAIN PODRIA APARECER UNA LISTA DE USUARIOS CON SUS DATOS Y UN BOTON PARA EDITARLOS O BORRARRLOS 
//UN BOTON PARA CREAR UN NUEVO USUARIO QUE TE LLEVE A UN FORMULARIO DE CREACION DE USUARIO
//UN BUSCADOR PARA BUSCAR USUARIOS POR NOMBRE O ID
//QUE TENGA UN ASIDE PARA ACCEDER A USUARIOS(QUE SEA LO QUE COMIENZA POR DEFECTO) Y PARA ACCEDER A TIKETS 
//ESTE ULTIMO ASIDE PODRIA SER UN MENU QUE SE DESPLIEGA AL HACER CLICK EN UN BONTON HAMBURGUESA
//EL MENU ASIDE DESPLEGABLE ENTOCES TIENE TRES APARTADOS: CREAR USUARIO, USUARIOS(MUESTRA A TOODOS LOS USUARIOS) Y TICKETS(MUESTRA TODOS LOS TICKETS)
